"""empty message

Revision ID: 12ebb2f02b6d
Revises: dad4942761f3
Create Date: 2019-09-22 10:43:06.715288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ebb2f02b6d'
down_revision = 'dad4942761f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cs50_glossary', sa.Column('delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cs50_glossary', 'delete')
    # ### end Alembic commands ###
