"""empty message

Revision ID: dad4942761f3
Revises: 
Create Date: 2019-09-22 01:20:06.139011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad4942761f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cs50_glossary',
    sa.Column('gid', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=True),
    sa.Column('translation', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('creator', sa.String(length=100), nullable=True),
    sa.Column('createtime', sa.Integer(), nullable=True),
    sa.Column('updater', sa.String(length=100), nullable=True),
    sa.Column('updatetime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('gid')
    )
    op.create_index(op.f('ix_cs50_glossary_word'), 'cs50_glossary', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cs50_glossary_word'), table_name='cs50_glossary')
    op.drop_table('cs50_glossary')
    # ### end Alembic commands ###
